dist: bionic
install:
- travis_retry sudo apt-get install -y python sudo wget xxd
- travis_retry wget https://deb.nodesource.com/setup_12.x -O /tmp/install-node.sh
- sudo sh /tmp/install-node.sh
- travis_retry sudo apt-get install -y nodejs
- travis_retry wget https://sdk.dfinity.org/install.sh -O /tmp/install-sdk.sh
- DFX_VERSION=0.4.12 sh -c 'yes Y | sh /tmp/install-sdk.sh'
- export PATH=/home/$USER/bin:$PATH
script:
- sh bootstrap.sh
- ID=$(xxd -p canisters/index/_canister.id)
- CRC=$(python -c "import crc8;h=crc8.crc8();h.update('$ID'.decode('hex'));print(h.hexdigest())")
- wget http://127.0.0.1:8000/?canisterId=ic:$ID$CRC
- cat index.html
